name: make tests

on:
  push:
    branches: [ "master", "main", "**", "**/**" ]
  pull_request:
    branches: [ "master", "main", "**", "**/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: |
          make
    - name: make test
      run: |
          make test
          git diff
    - name: make tests
      run: |
          make tests
          git diff
    - name: make tests-10000X
      run: |
          make tests-10000X
          git diff
    - name: pi
      run: ./pi
